### ISSUE TITLE
2.3.0 slightly changes color value

### ISSUE THREAD

**Issue by unional** [bpostlethwaite/colormap#16]
Hi, I notice the generated color in 2.3.0 is slightly different than 2.2.0.

Is this intentional?

https://travis-ci.org/unional/color-map/builds/280895167?utm_source=github_status&utm_medium=notification

Thanks. 🌷

**Comment by dfcreative** [comment]
@unional yes, it is, and indeed proper behavior. Before it generated duplicated colors due to wrong interpolation:
![image](https://user-images.githubusercontent.com/300067/30975878-538da3c0-a441-11e7-9b1d-2943f501a16e.png)

Now it is fixed:
![image](https://user-images.githubusercontent.com/300067/30975899-6514837a-a441-11e7-8f3c-af918948e642.png)

Please close if that is what you are addressing.

**Comment by unional** [comment]
I think it is a different issue.
It's the alpha that is slightly off.
Nothing major, just want to confirm if that is intentional.

```sh
    [
        0,
        241,
        135,
  -     0.943661971830986,
  +     0.9436619718309859,
      ]
```

**Comment by dfcreative** [comment]
That is unintentional, but seems to be related to changed interpolation too. Although considering such precision is there a sense for such rigid comparison?

**Comment by unional** [comment]
Not really. :)
I was using `colormap` to validate my implementation, that's all. 🌷
