### ISSUE TITLE
Duplicate keys for cool

### ISSUE THREAD

**Issue by archmoj** [bpostlethwaite/colormap#27]
Originally reported in https://github.com/plotly/plotly.js/issues/5457

Which "cool" is the cool?
https://github.com/bpostlethwaite/colormap/blob/cb22a04d23b9fd47a6663d80d44ad77594bd394a/colorScale.js#L8
Or 
https://github.com/bpostlethwaite/colormap/blob/cb22a04d23b9fd47a6663d80d44ad77594bd394a/colorScale.js#L58

**Comment by archmoj** [comment]
Both added around the same time.
```
$ git blame colorScale.js -L8,+1
b0502b98 colorScales.js (Dmitry 2016-05-20 18:57:21 -0400 8)    "cool":[{"index":0,"rgb":[0,255,255]},{"index":1,"rgb":[255,0,255]}],
```
```
$ git blame colorScale.js -L58,+1
1601f158 colorScales.js (Dmitry 2016-05-20 19:46:44 -0400 58)   "cool": [{"index":0,"rgb":[125,0,179]},{"index":0.13,"rgb":[116,0,218]},{"index":0.25,"rgb":[98,74,237]},{"index":0.38,"rgb":[68,146,231]},{"index":0.5,"rgb":[0,204,197]},{"index":0.63,"rgb":[0,247,146]},{"index":0.75,"rgb":[0,255,88]},{"index":0.88,"rgb":[40,255,8]},{"index":1,"rgb":[147,255,0]}],
```

@alexcjohnson seems like we could safely remove the first one, right?

**Comment by archmoj** [comment]
Actually it is the side effect of #6.

**Comment by archmoj** [comment]
BTW the first cool appear to be similar to matlab's: https://www.mathworks.com/help/matlab/ref/cool.html

cc: @dy

**Comment by alexcjohnson** [comment]
Yes, we can certainly drop the first one - it's been there for nearly 5 years so recent backward compatibility is more important than original intent at this point.

It's a bit unfortunate that plotly.js includes these scales at all though, since it's a different set than [we already have](https://github.com/plotly/plotly.js/blob/master/src/components/colorscale/scales.js) - a lot of overlap but some differences and different conventions. Are there cases where `surface`, `cone`, or `mesh` (those are the places this is referenced according to `npm ls colormap`) can access these scales rather than the ones we define within plotly.js?

There are a lot more scales here that we don't include, but the parts we have that this package misses:
- `Cividis`
- `Blues`
- `Reds`
- This package still has the typos `yignbu` and `yiorrd` instead of `ylgnbu` and `ylorrd`
